### PR TITLE
Reverting Twig Extensions dependency to 1.2 to prevent legacy sites from breaking

### PR DESCRIPTION
**Pull request by emudojo**
**Error Message:**

Message Error: Class 'Jasny\Twig\PcreExtension' not found in islandora_multi_importer_twig_form() (line 575 of /var/www/html/web/sites/all/modules/islandora/islandora_multi_importer/includes/import.form.inc).

**Problem:**
Twig Extensions updated to a breaking version, and the module needs a small rewrite on as tokenize no longer accepts a string as its main parameter

**Suggested Solution**
and now it has to be like
$stream = $twig->tokenize(new \Twig\Source($source, $identifier));
https://twig.symfony.com/doc/2.x/internals.html

this patch sets the twig extensions version and dependencies to be compliant with the mod

### CODE REVIEW

**Comment by DiegoPino** [comment]
@emudojo question: are you running composer install or update? Because we have everything fixed to Twig 1.x to allow older systems (like php from previous centuries) to run this
See https://github.com/mnylc/islandora_multi_importer/blob/master/composer.lock#L620

**Comment by DiegoPino** [comment]
Maybe i'm missing something else also, so feel free to follow up with more explanations. Thanks!

**Comment by emudojo** [comment]
always composer install, on an automated build that started to fail a few weeks ago, this fix to a set release addressed the problem for us, but we don't want to keep a fork, so I just leave it here for consideration.

it should not  introduce any regressions but it might need some extra testing.

**Comment by DiegoPino** [comment]
@emudojo thanks. I need to test this. I understand the change but the lock has a lot of changes that could affect people with saved settings (google API) and other workflow problems with existing data. Will follow up with this once i get some time, prob. not before the end of the week. Thanks a lot!

**Pull request closed without merging**
