### PR TITLE
ISSUE-60

### PR DESCRIPTION
**Pull request by DiegoPino**
@Natkeeran hopefully this fixes the issues with RELS-INT and RELS-EXT.
PLEASE don’t test on important objects. Only do a simple test first.
This approach is new, means it creates all RDF relationships from scratch and generates a new version of those 2 datastreams on existing objects. I'm not sure if this is what you want really. The danger is it will not include any existing properties at all, only fresh ones. If you want that: means preserve all predicates that are in there and only add new ones, I can do that also. But not sure if that should be default behaviour? Also, not sure which predicates you think would still be relevant after a parent change, or even a few missing datastreams? (like what is inside RELS-INT?)

### CODE REVIEW

**Comment by Natkeeran** [comment]
@DiegoPino Thank you.  I will test this tomorrow.

**Comment by Natkeeran** [comment]
@DiegoPino 

Getting the following error with this PR:
```
Target Object <em class="placeholder">dsu:155</em> does not exists, update errored. 
```
I am not sure what is the range of properties that can be added to the RELS-EXT.  i.e `<islandora:create_pdf>true</islandora:create_pdf>` and `<islandora:isUserManagementRule>TRUE</islandora:isUserManagementRule>`)? I assume, some modules may have added additional RELS-EXT properties.  

The current default behavior to add/modify only relevant relationships seems good.  We may have to handle the `islandora:inheritXacmlFrom` case as a special case.  As you noted, this seems to be a [bug?](https://github.com/Islandora/islandora_xacml_editor/blob/9f40954f4e6a6ef3d440ab9f316b1ca69c2cb5b3/islandora_xacml_editor.module#L428-L434). From what I understand, there can only be one applicable inheritXacmlFrom statement.  Thus, we can remove all existing inheritXacmlFrom elements and apply the xacml policy on update.

**Comment by DiegoPino** [comment]
@Natkeeran and object with PID dsu:155 exist?
I will work more on this tonight. probably better to just remove the same properties i'm updating?

**Comment by Natkeeran** [comment]
@DiegoPino Even though I am trying to update, it seems to be trying to create it.  dsu:155 does not exist.  

Removing the same properties that are being updated would work.  In that case, would need to support a way to include an item into multiple collections.

**Comment by DiegoPino** [comment]
hu! Ok. Weird. Let me deal with this tonight. So sorry. Just got stuck on docker stuff so can't debug right now. Promise you will have this solved by tomorrow.

**Comment by Natkeeran** [comment]
@DiegoPino 

Getting an exception.  IN this case the pid exists and correct:
```
DatastreamExistsException: The datastream RELS-EXT already exists on the object gundagunde:18920 in NewFedoraObject->ingestDatastream() (line 573 of /var/www/gundagunde/sites/all/libraries/tuque/Object.php).
```

**Comment by DiegoPino** [comment]
@Natkeeran still testing. Give a while and I will let you know when ready

**Comment by DiegoPino** [comment]
@Natkeeran hu!.  Well 9 commits later and no warnings anymore and i managed to update 3 objecs.

 I wrote this piece during a conference so it made a lot of mistakes (just excuses, i know!)

Could you give it a spin when you have time? Maybe you can find more issues

I'm committing tomorrow the "Settings Save" option (yes, no going through eternal select boxes every time!) and will remove also some comments. I want to be sure that you at least are going to the next level with this changes and can update again.

Side note: With these changes, I can allow now CMODEL transmutation! (@mcfatem), means you can move from Content model to another. I have that explicitly disabled here
https://github.com/mnylc/islandora_multi_importer/blob/a675ba64a57b770035b51844868d40c26bd892db/includes/islandora_multi_batch.inc#L528-L536

but, if any of you have a very good argument for needing it I can enable that and make it part of the UI.

Finally @Natkeeran, with this the new behavior is to create a new RELS-EXT from scratch on an update. I will add a toggle for that, in case you want to preserve custom RDF properties not provided by IMI. Enjoy!

**Comment by Natkeeran** [comment]
@DiegoPino sorry for the delayed testing here.  

For update it seems to be creating a new object
```
dsu:161 | Error | Target Object <em class="placeholder">dsu:161</em> does not exists, update errored.
```
No other error in the drupal or apache logs.

**Comment by DiegoPino** [comment]
Nat, are you sure? does dsu:161 exist? Was dsu:161 your desired PID?
Did you remove any sets containing the PID you wanted to update that was left over from a previous ingest? Islandora Batch only allows a single PID to exist inside the database. Which means in case the PID you want to update was previously inside the DB for an e.g ingest, it will fail of course.

I tested locally without issues, so i will need more feedback.

let me know (or lets have a interactive session if you want to)

best

Diego Pino Navarro
Metropolitan New York Library Council
599 11th Av. New York, NY 10036

**Comment by Natkeeran** [comment]
@DiegoPino 

No,  dsu:161 does not exist.  I've attached the csv.  It is trying to update gundagunde:18920.  That object already exists in pre prod.  

If it is easier, I can screen share via skype when you get a moment.

**Comment by DiegoPino** [comment]
Ok, will try to find you on skype in 1:30 hours more (3:00 EST) is that good for you? Thanks!

**Comment by Natkeeran** [comment]
@DiegoPino Sure, thanks.

**Comment by DiegoPino** [comment]
@Natkeeran just to keep any lurkers updated: 👍 we tested and changes on this pull are good to go. I will merge into the main branch now.

**Pull request merged**
