### PR TITLE
Issue 72

### PR DESCRIPTION
**Pull request by DiegoPino**
Fix some leftover issues from the last big refactor. (Issue 60)

This pull fixes:
A badly used file accumulator

This pull adds:

Better error reporting on Twig template editing when something goes wrong. Only applies to the template manager at /admin/islandora

This pull corrects:
Some documentation

### CODE REVIEW

**Comment by DiegoPino** [comment]
@McFateM @petermacdonald  @Natkeeran @aksm

This pull corrects a lot of issues with 

- handling temporary managed files and making sure they get removed once the batch sets get removed (i'm looking at you Peter and Albert)
- Datastreams creation if source files don't exist (guess what, now they will no longer be created)
- Better multiple attempts to get remote files
- Use HTTP headers and mime type detection of extension (if present) when getting remote files
- Wrappers like public://, private:// should work out of the box
- Error reporting (i could still need some advice on that, formatting watchdog messages...)
- Miscellaneous goodies.

This should address #72 and other issues

I know I have still a long road ahead to make this failsafe and perfect, but we are getting closer!

Could any of you please test with a spreadsheet similar to https://docs.google.com/spreadsheets/d/1yOMLTwQ6lO_2iTzT-eHcHqEvzhNbCpKB1wGpjlouaRI/edit#gid=0? and a nice Zip file? without ZIP file would be good

Will merge once I get some feedback. Please inform any ICG/ISLE member that is using this too.

Thanks!

**Comment by DiegoPino** [comment]
@McFateM ping. Before going rogue/amazing with that book hook, can you give this pull a test? I just rebased and cleaned up and force pushed, should apply cleanly over master (after your lastest merge). There is a lot happening here.

**Comment by DiegoPino** [comment]
@McFateMI will do some internal testing tonight and will merge tomorrow. I need to have some of the issues this one solves merged to help folks deal with non tracked managed files.

**Comment by McFateM** [comment]
Just FYI... I did pull the latest code and gave it a test, of sorts, by trying to ingest a book with my hook engaged.  The hook didn't work (yet) but the rest of the ingest process via IMI went smoothly.  This particular test used a "local*" file and my hook implementation for fetching that file from a mapped CIFS share.

**Pull request merged**
